"""Vehicle Intelligence, Detections, Tracks, ANPR Plates, and Embeddings Models."""

from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import BigInteger, DateTime, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.alert import Alert
    from app.models.camera import Camera


class VehicleDetection(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Raw bounding box detection from AI detector (e.g. YOLOX)."""

    __tablename__ = "vehicle_detections"

    camera_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("cameras.id", ondelete="CASCADE"), index=True, nullable=False
    )
    frame_number: Mapped[int] = mapped_column(BigInteger, default=0, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True, nullable=False)
    vehicle_class: Mapped[str] = mapped_column(
        String(50), index=True, nullable=False
    )  # car, motorcycle, bus, truck
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    bbox_x1: Mapped[float] = mapped_column(Float, nullable=False)
    bbox_y1: Mapped[float] = mapped_column(Float, nullable=False)
    bbox_x2: Mapped[float] = mapped_column(Float, nullable=False)
    bbox_y2: Mapped[float] = mapped_column(Float, nullable=False)


class VehicleTrack(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Multi-frame vehicle track generated by ByteTrack within a single camera."""

    __tablename__ = "vehicle_tracks"

    camera_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("cameras.id", ondelete="CASCADE"), index=True, nullable=False
    )
    track_id: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    first_seen: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), index=True, nullable=False
    )
    last_seen: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True, nullable=False)
    vehicle_class: Mapped[str] = mapped_column(String(50), nullable=False)
    total_frames: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    direction: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True
    )  # NORTH, SOUTH, EAST, WEST


class VehicleEvent(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Primary Searchable Vehicle Intelligence Event (The Core Search Index Unit)."""

    __tablename__ = "vehicle_events"

    camera_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("cameras.id", ondelete="CASCADE"), index=True, nullable=False
    )
    track_id: Mapped[Optional[str]] = mapped_column(String(100), index=True, nullable=True)

    event_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), index=True, nullable=False
    )
    source_pts: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)

    # License Plate Recognition (ANPR)
    plate_raw: Mapped[Optional[str]] = mapped_column(String(50), index=True, nullable=True)
    plate_normalized: Mapped[Optional[str]] = mapped_column(String(50), index=True, nullable=True)
    plate_confidence: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Vehicle Visual Attributes
    vehicle_class: Mapped[str] = mapped_column(
        String(50), default="car", index=True, nullable=False
    )
    vehicle_color: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    detection_confidence: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # Geospatial Context (Mirrored from camera at event time for fast spatial queries)
    latitude: Mapped[float] = mapped_column(Float, index=True, nullable=False)
    longitude: Mapped[float] = mapped_column(Float, index=True, nullable=False)
    location_name: Mapped[str] = mapped_column(String(255), default="", nullable=False)

    # Bounding Box coordinates
    bbox_x1: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    bbox_y1: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    bbox_x2: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    bbox_y2: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # Evidence Reference
    snapshot_path: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # Relationships with selectin loading for async safety
    camera: Mapped["Camera"] = relationship(
        "Camera", back_populates="vehicle_events", lazy="selectin"
    )
    plates: Mapped[List["VehiclePlate"]] = relationship(
        "VehiclePlate", back_populates="event", cascade="all, delete-orphan", lazy="selectin"
    )
    embedding: Mapped[Optional["VehicleEmbedding"]] = relationship(
        "VehicleEmbedding",
        back_populates="event",
        uselist=False,
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    alerts: Mapped[List["Alert"]] = relationship("Alert", back_populates="event", lazy="selectin")

    __table_args__ = (
        Index("ix_vehicle_events_plate_time", "plate_normalized", "event_time"),
        Index("ix_vehicle_events_cam_time", "camera_id", "event_time"),
        Index("ix_vehicle_events_spatial", "latitude", "longitude"),
    )


class VehiclePlate(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Detailed OCR candidate reading associated with a vehicle detection."""

    __tablename__ = "vehicle_plates"

    event_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("vehicle_events.id", ondelete="CASCADE"), index=True, nullable=False
    )
    plate_text: Mapped[str] = mapped_column(String(50), index=True, nullable=False)
    plate_normalized: Mapped[str] = mapped_column(String(50), index=True, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    crop_path: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    event: Mapped[VehicleEvent] = relationship(
        "VehicleEvent", back_populates="plates", lazy="selectin"
    )


class VehicleEmbedding(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Visual appearance feature vector for Cross-Camera Vehicle Re-ID."""

    __tablename__ = "vehicle_embeddings"

    event_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("vehicle_events.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    model_name: Mapped[str] = mapped_column(String(100), default="OSNet-x0.25", nullable=False)
    embedding_dim: Mapped[int] = mapped_column(Integer, default=512, nullable=False)
    # Stored as serialized JSON string for SQLite dev fallback; compatible with pgvector in Postgres
    vector_data: Mapped[str] = mapped_column(Text, nullable=False)

    event: Mapped[VehicleEvent] = relationship(
        "VehicleEvent", back_populates="embedding", lazy="selectin"
    )
