import React from 'react';
import { Clock, Eye, CheckCircle } from 'lucide-react';
import { AlertItem } from '../types';
import { Button } from '../components/common/Button';
import { PriorityBadge, StatusBadge, CategoryBadge } from '../components/common/Badge';

interface AlertsPageProps {
  alerts: AlertItem[];
  onAcknowledgeAlert: (alertId: string) => void;
  onTrackPlate: (plate: string) => void;
}

export const AlertsPage: React.FC<AlertsPageProps> = ({
  alerts,
  onAcknowledgeAlert,
  onTrackPlate,
}) => {
  return (
    <div className="space-y-6">
      <div className="bg-[#180a10] p-6 rounded-2xl border border-rose-600/50 shadow-2xl flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2 py-0.5 rounded bg-rose-500/20 text-rose-300 font-mono text-xs font-bold border border-rose-500/30">
              REAL-TIME DISPATCH HUB
            </span>
            <span className="text-xs font-mono text-rose-400 animate-pulse">
              ● WEBSOCKET CONNECTION LIVE (&lt; 500MS DISPATCH)
            </span>
          </div>
          <h1 className="text-xl font-black text-white font-mono tracking-wide mt-1">
            SECURITY ALERTS & HOTLIST TRIAGE
          </h1>
          <p className="text-xs text-slate-300 mt-1">
            Immediate notifications generated by automated license plate and Re-ID cross-correlation
          </p>
        </div>
      </div>

      {/* Alert Feed Cards */}
      <div className="space-y-4">
        {alerts.map((alert) => (
          <div
            key={alert.id}
            className={`p-6 rounded-2xl border transition-all ${
              alert.status === 'NEW'
                ? 'bg-[#120a10] border-rose-600/60 shadow-[0_0_20px_rgba(244,63,94,0.2)]'
                : 'bg-[#0a0f1d] border-slate-800'
            }`}
          >
            <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 pb-4 border-b border-slate-800/80">
              <div className="flex items-center gap-3">
                <span className="px-3.5 py-1.5 rounded-lg bg-black border border-yellow-500/70 text-yellow-300 font-mono font-black text-lg tracking-wider shadow-md">
                  {alert.plate_number}
                </span>
                <PriorityBadge priority={alert.priority} />
                <CategoryBadge category={alert.category} />
                <StatusBadge status={alert.status} />
              </div>

              <div className="flex items-center gap-2 text-xs font-mono text-slate-400">
                <Clock className="h-4 w-4 text-blue-400" />
                <span>{new Date(alert.timestamp).toLocaleString()}</span>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 py-4 text-xs font-mono">
              <div>
                <span className="text-slate-400 block text-[10px]">WATCHLIST RULE</span>
                <span className="text-white font-bold">{alert.watchlist_name}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-[10px]">DETECTED CAMERA</span>
                <span className="text-white font-bold">{alert.camera_name} ({alert.location})</span>
              </div>
              <div>
                <span className="text-slate-400 block text-[10px]">CASE REFERENCE</span>
                <span className="text-amber-400 font-bold">{alert.case_number || 'N/A'}</span>
              </div>
            </div>

            <div className="flex flex-wrap items-center justify-between gap-4 pt-3 border-t border-slate-800/80">
              <div className="text-[11px] font-mono text-slate-400">
                {alert.acknowledged_by ? (
                  <span className="text-emerald-400">
                    ✓ Acknowledged by {alert.acknowledged_by} at{' '}
                    {alert.acknowledged_at && new Date(alert.acknowledged_at).toLocaleTimeString()}
                  </span>
                ) : (
                  <span className="text-rose-400 font-bold animate-pulse">
                    ● PENDING IMMEDIATE OFFICER REVIEW
                  </span>
                )}
              </div>

              <div className="flex items-center gap-3">
                <Button
                  variant="outline"
                  size="sm"
                  icon={<Eye className="h-3.5 w-3.5" />}
                  onClick={() => onTrackPlate(alert.plate_number)}
                >
                  Track Movement
                </Button>
                {alert.status === 'NEW' && (
                  <Button
                    variant="warning"
                    size="sm"
                    icon={<CheckCircle className="h-3.5 w-3.5" />}
                    onClick={() => onAcknowledgeAlert(alert.id)}
                  >
                    Acknowledge Alert
                  </Button>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
